### Add first user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user",
  "name": "Alice",
  "password": "password123"
}

### Add second user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user2",
  "name": "Bob",
  "password": "securepass456"
}