DELETE http://localhost:3003/api/blogs/69009e7ecffa412e667c4840
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVybm8iLCJpZCI6IjY4ZWRmMWYyNmI5YWI0MjMwMzJkZmMyZSIsImlhdCI6MTc2MTY0ODE0NywiZXhwIjoxNzYxNjUxNzQ3fQ.wCxGWSjS9k215DNAi6RRoA3Sor_IgJ-h-oIMZehT9k0


